### ISSUE TITLE
punycode.toASCII places `xn--` before http or https

### ISSUE THREAD

**Issue by redlpd** [bestiejs/punycode.js#110]
Tried using punnycode.toASCII like this:
`punycode.toASCII('https://sample.com');`

Actual result:
`xn--https://ggl-ykj0ia.com`

Expected result:
`https://xn--ggl-ykj0ia.com`

**Comment by Hazmi35** [comment]
Same issue here

**Comment by mathiasbynens** [comment]
Yeah, you’re supposed to only pass it the domain name, not a full URL including a schema like `http://` or `https://`. See the docs: https://github.com/bestiejs/punycode.js#punycodetoasciiinput
