### ISSUE TITLE
Should `toASCII` lowercase the input first?

### ISSUE THREAD

**Issue by sgalinski** [bestiejs/punycode.js#26]
Code: `punycode.toASCII('ОРГ.eu')`
Expected: `xn--c1avg.eu`
Returned: `xn--f0avg.eu`

**Comment by mathiasbynens** [comment]
Workaround is to lowercase first before passing to `punycode.toASCII`.

**Comment by mathiasbynens** [comment]
`toASCII` aims to follow the specification here which doesn’t include lowercasing: https://tools.ietf.org/html/rfc3490#section-4.1

I’ll add a note to the README. Thanks!

**Comment by indolering** [comment]
Just wanted to note that you should probably be using toLocaleLowerCase().
