### ISSUE TITLE
Modularization

### ISSUE THREAD

**Issue by medikoo** [bestiejs/punycode.js#28]
Will you consider a PR that will split this package into multiple modules?

e.g. at this point when I just want to use `encode` I need to import module that also comes with `decode` and some other stuff. It'll be great to have possibility to import just `encode` related logic in that case.

I envision it so content of this package is organized as:
- `lib` (folder for common modules used by more than one of modules below)
- `usc2` (folder)
  - `decode.js`
  - `encode.js`
- `toASCII.js`
- `decode.js`
- `encode.js`
- `toUnicode.js`
- `index.js` (exports all modules, and result of it would be same as of requiring `punycode` now)

**Comment by mathiasbynens** [comment]
Since punycode.js is included as-is in Node.js & io.js doing so would complicate the upstreaming process.

I’d rather not do this. 

The most common standalone functionality is probably `ucs2.encode` and `ucs2.decode`, but ES6 `String.fromCodePoint` ([polyfill](https://mths.be/fromcodepoint)) and `String#codePointAt` (](https://mths.be/codepointat)) solve the same problem. If you need modularity, why not use those?

**Comment by medikoo** [comment]
Thanks @mathiasbynens, all understood.

I've actually wanted to use some stuff from node's url module, which I started to modularize to not take it in full into browser, but then I found it also needs `punycode.toASCII` and imports full `punycode` for that, this directed me here :)

I'll probably just prepare modular versions of two projects, for my needs. That would at least solve the problem on my side.

**Comment by mathiasbynens** [comment]
Sounds good! :+1: 

Please leave a link to those projects here once they’re done.

**Comment by medikoo** [comment]
I published modular version as [punycode2](https://www.npmjs.com/package/punycode2). Same way I published modular versions of other node.js modules: [url3](https://www.npmjs.com/package/url3), [querystring2](https://www.npmjs.com/package/querystring2) and a while ago [path2](https://www.npmjs.com/package/path2)
