### ISSUE TITLE
Is punycode.decode() a reasonable test for valid punycode FQDNs?

### ISSUE THREAD

**Issue by mikemaccana** [bestiejs/punycode.js#30]
I'm trying to check if a hostname string is a valid punycode/non-punycode FQDN. I can see that running:

     punycode.decode('☃')

Properly throws a RangeError which seems like it. But as this is a complex spec and I'm not sure after reading the docs: would `punycode.decode()` be considered a reasonable test of whether a string contains characters that would be invalid for punycode?

I'm aware of other restrictions on URLs, eg, string length.

**Comment by indolering** [comment]
Well `decode` is for converting Punycode ASCII labels into Unicode labels, so throwing any non-ASCII text into decode should throw an error.  If you are starting with a string that may contain non-ASCII characters, run it through `toASCII`, which should throw an error if any characters are not allowed.

**Comment by mathiasbynens** [comment]
What @indolering said.

**Comment by indolering** [comment]
Having just figured out that domain name labels are supposed to be passed through Nameprep first, I think the answer to this question is "no" or at least "Don't use punycode.js to lint unicode DNS labels because it doesn't perform normalization."

**Comment by mikemaccana** [comment]
Thanks @indolering! I kind of felt but couldn't turn into words what was wrong with the previous answer. I now *think* punicode only does punicode, i.e. it has no idea what a valid domain name is. I'll check out nameprep too!

**Comment by mikemaccana** [comment]
I gather nameprep is this spec: https://en.wikipedia.org/wiki/Nameprep ?

**Comment by mathiasbynens** [comment]
@mikemaccana Correct.

https://github.com/mathiasbynens/todo/issues/9 seems relevant.
