### ISSUE TITLE
error occurring in SourceTree

### ISSUE THREAD

**Issue by lmaharas** [bestiejs/punycode.js#31]
is anyone else seeing this error from time to time?

'git status' failed with code 128:'fatal: Not a git repository: /Users/Mathias/Projects/punycode.js/.git/modules/vendor/docdown'

Not sure how it's being triggered.  Any ideas?  
Found a related issue here: https://github.com/davidguttman/cssify/issues/18

**Comment by mathiasbynens** [comment]
Duplicate of #21.

**Comment by isiegel** [comment]
I'm seeing the same issue.

**Comment by lmaharas** [comment]
@isiegel, I found this [comment in issue #21] (https://github.com/bestiejs/punycode.js/issues/21#issuecomment-43902544) helpful.  I disable a few unused node modules in my project that referenced punycode@1.0.0.  Good luck!
