### ISSUE TITLE
punycode with prefix "http://"

### ISSUE THREAD

**Issue by user51ru** [bestiejs/punycode.js#34]
Hi, if you want to use unicod with the prefix "http:// | https:// | or not" then you should replace the function

```js
function mapDomain(string, fn) {
	var parts = string.split('@');
	var result = '';
	if (parts.length > 1) {
		result = parts[0] + '@';
		string = parts[1];
	}
	tmp = string.match(/(^https?:\/\/)?(.*)/);
	string = tmp[2].replace(regexSeparators, '\x2E');
	var labels = string.split('.');
	var encoded = map(labels, fn).join('.');
	return result + (!!tmp[1] ? tmp[1] : '') + encoded;
}
```

P.S> sorry my bad english :)

**Comment by mathiasbynens** [comment]
`toUnicode` and `toASCII` deal with domain name labels rather than full URLs by design. If you need this, consider implementing parsing the URL and extracting the host before passing it to Punycode.js.
