### ISSUE TITLE
Punycode Reader for Linux

### ISSUE THREAD

**Issue by Nitin29** [bestiejs/punycode.js#37]
Hi All,

I don't know whether its a right platform to post this, please forgive me.

We are using postfix for IDN email startup services.

While we are sending mail using our postfix server to our gmail id in gmail inbox it shows in a perfect manner from "नितिन@निक्सी.भारत" sharing image.

But in while we are doing postfix to postfix communication or other webmail it shows localpart in perfect but domain part in punycode sharing image as well

Looking for support please.

Nitin

![idn email format in gmail](https://cloud.githubusercontent.com/assets/13060540/9991132/e903809e-6084-11e5-9ff5-b2406b15676e.png)
![idn email format in postfix](https://cloud.githubusercontent.com/assets/13060540/9991133/e904bd74-6084-11e5-9543-c625b129712a.png)

**Comment by mathiasbynens** [comment]
https://github.com/bestiejs/punycode.js/issues/20#issuecomment-51509669

**Comment by mathiasbynens** [comment]
This is working as intended.
