### ISSUE TITLE
Wrong conversion to ASCII of IDN emails separated by spaces

### ISSUE THREAD

**Issue by marbug** [bestiejs/punycode.js#39]
Hello.

$subj

Please try to convert to ASCII a string of several IDN emails separated by spaces.
For example, these ones:

punycode.toASCII("user@мой.домен user@домен.уа user@домен.рф user@dömäin.example");

As a result you'll see a wrong value. For a string above it is:
"user@xn--i1afg.xn-- user-sweh9ckh"

But separately these values are converted to:

punycode.toASCII("user@мой.домен");
"user@xn--i1afg.xn--d1acufc"

punycode.toASCII("user@домен.уа");
"user@xn--d1acufc.xn--80a1b"

punycode.toASCII("user@домен.рф");
"user@xn--d1acufc.xn--p1ai"

punycode.toASCII("user@dömäin.example");
"user@xn--dmin-moa0i.example"

As I understand the result of
punycode.toASCII("user@мой.домен user@домен.уа user@домен.рф user@dömäin.example");
should be the same line, i.e.
"user@мой.домен user@домен.уа user@домен.рф user@dömäin.example"

Please confirm/fix.

P.S. Reproduced in Chrome 46.0.2490.80 and FireFox 42.0 (under Windows and Kubuntu)

**Comment by mathiasbynens** [comment]
https://github.com/bestiejs/punycode.js#punycodetoasciiinput

The parameter passed to `toASCII` is supposed to represent a *single* domain name or email address.
