### ISSUE TITLE
Problem with latest version(ES6 not work in browser)

### ISSUE THREAD

**Issue by ximet** [bestiejs/punycode.js#50]
Sided lib pulling punycode.js. In webpack setting for babel-loader - all external lib ignore for babel. And I have problem with punycode lib: he return error don't parse this string: 
const ucs2encode = array =>String.fromCodePoint(...array).

I resolve problem: add to my project old version punycode("punycode": "~1.4.1"), but it's hack, because for my project this dependency not needed. How fix it?

**Comment by mathiasbynens** [comment]
> […] but it's hack […]

It’s not a hack.

From [the README](https://github.com/bestiejs/punycode.js#readme):

> The current version supports recent versions of Node.js only. For the old version that offers the same functionality with broader support, including Rhino, Ringo, Narwhal, and web browsers, see [v1.4.1](https://github.com/bestiejs/punycode.js/releases/tag/v1.4.1).
