### ISSUE TITLE
SyntaxError: missing = in const declaration

### ISSUE THREAD

**Issue by athomann** [bestiejs/punycode.js#52]
In firefox version 47.01 . I get the error "SyntaxError: missing = in const declaration" for punycode line 301

This stalls my app completely.

`	
// Handle the basic code points.
	for (const currentValue of input) {
		if (currentValue < 0x80) {
			output.push(stringFromCharCode(currentValue));
		}
	}
`

**Comment by mathiasbynens** [comment]
From the README:

> The current version supports recent versions of Node.js only. For the old version that offers the same functionality with broader support, including Rhino, Ringo, Narwhal, and web browsers, see [v1.4.1](https://github.com/bestiejs/punycode.js/releases/tag/v1.4.1).

**Comment by katsos** [comment]
Same error exists with NodeJS version 6.3.1 on Firefox 48.0.

**Comment by mathiasbynens** [comment]
Here’s the Firefox bug you’re seeing: https://bugzilla.mozilla.org/show_bug.cgi?id=449811

Anyway, `GOTO` https://github.com/bestiejs/punycode.js/issues/52#issuecomment-232867184.
