### ISSUE TITLE
Wrong conversion of url with non-ASCII symbols

### ISSUE THREAD

**Issue by skadermen** [bestiejs/punycode.js#54]
Convert using .toASCII method:
Example 1
Input: http://мой-отличный-сайт.рф
Output: xn--http://---8yh0gkccznvnc9dpi2i8d.xn--p1ai

Example 2
Input: http://example.com/и_часть_на_русском
Output: http://example.xn--com/___-6fgb0f1ayjr2alfamz9exf

But here https://www.punycoder.com/ all examples converts normally.

**Comment by mathiasbynens** [comment]
https://github.com/bestiejs/punycode.js#punycodetoasciiinput

`toASCII` takes a domain name, so don’t include `http://`.
