### ISSUE TITLE
ES6 Module?

### ISSUE THREAD

**Issue by nathanhammond** [bestiejs/punycode.js#55]
Would you be willing to accept a PR which implemented a prepublish step to generate both an ES6 module and a CommonJS module? I don't believe that this is against the spirit of dropping support for old environments a la #48 and is in this case exactly one line different.

**Comment by mathiasbynens** [comment]
Sounds good. Send over the PR and I’ll take a look!

**Comment by nathanhammond** [comment]
K, on it. :)
