### ISSUE TITLE
Syntax error in IE 11

### ISSUE THREAD

**Issue by Aspedm** [bestiejs/punycode.js#56]
Got error  "syntax error punycode.js" in IE 11.
string 133:  const ucs2encode = array => String.fromCodePoint(...array);

**Comment by mathiasbynens** [comment]
See the README:

> The current version supports recent versions of Node.js only. For the old version that offers the same functionality with broader support, including Rhino, Ringo, Narwhal, and web browsers, see [v1.4.1](https://github.com/bestiejs/punycode.js/releases/tag/v1.4.1).

**Comment by Aspedm** [comment]
Yep. It's my mistake.
