### ISSUE TITLE
Decoding profession emojis 👩🏽‍🚀

### ISSUE THREAD

**Issue by suprMax** [bestiejs/punycode.js#68]
I've been using this library to check the length of unicode strings and shorten them, and assumed it was a good way to deal with emojis nonsense. However, recently I've stumbled upon this:

```
> p.ucs2.decode('👩🏽‍🚀')
[ 128105, 127997, 8205, 128640 ]
> p.ucs2.decode('💩')
[ 128169 ]
```

I understand that these new emojis consist if multiple characters and my solution was ultimately flawed.

I was wondering that perhaps there is a way to still group them into one symbol somehow, given that they do appear as one when displayed? Something like this would help me solve my problems, I think:

```
> p.ucs2.decode('hello 👩🏽‍🚀 world')
[ 104,
  101,
  108,
  108,
  111,
  32,
  [ 128105, 127997, 8205, 128640 ],
  32,
  119,
  111,
  114,
  108,
  100 ]
```

**Comment by demurgos** [comment]
This library is dealing with code points. I recommend you to look into grapheme clusters for your issue.

**Comment by suprMax** [comment]
That would do the trick, thanks!
