### ISSUE TITLE
punycode.js is on ES6

### ISSUE THREAD

**Issue by letoss** [bestiejs/punycode.js#72]
Hello.

I just updated twitter-text library. This lib has as dependency punycode. After this update, my phantom test browser started falling because a "const" syntax error. After a little research, I realized that the problem came from this lib.

I saw that there are two files in the library folder: punycode.js and punycode.es6.js. I renamed punycode.es6.js but I still getting the syntax error. So, I decided to open punycode.js and I found that it has been written in es6 too!

```
$ cat punycode/punycode.js 
'use strict';

/** Highest positive signed 32-bit float value */
const maxInt = 2147483647; // aka. 0x7FFFFFFF or 2^31-1

/** Bootstring parameters */
const base = 36;
const tMin = 1;
const tMax = 26;
const skew = 38;
const damp = 700;
const initialBias = 72;
const initialN = 128; // 0x80
const delimiter = '-'; // '\x2D'

/** Regular expressions */
const regexPunycode = /^xn--/;
const regexNonASCII = /[^\0-\x7E]/; // non-ASCII chars
const regexSeparators = /[\x2E\u3002\uFF0E\uFF61]/g; // RFC 3490 separators

/** Error messages */
const errors = {
	'overflow': 'Overflow: input needs wider integers to process',
	'not-basic': 'Illegal input >= 0x80 (not a basic code point)',
	'invalid-input': 'Invalid input'
};

...
```

Is there any way to update this and make punycode.js to be written in pure JS?

Thank you very much.

**Comment by conocono** [comment]
Have you tried building it with webpack?

**Comment by letoss** [comment]
I found a workaround. I had to compile the lib with webpack excluding the punycode lib from babel loader.
`exclude: [/node_modules\/(?!(punycode))/]`

**Comment by jimmywarting** [comment]
How about switching to headless chrome instead? 
phantomjs is not really a browser, nobody is using it and it's far behind any other browser. It was made for developers to do automated testing and stuff.

**Comment by letoss** [comment]
@jimmywarting I can review that option too. Thanks for it. Anyway, I develop a web app, one of the requirements is to run in IE11. IE11 doesn't understand ES6, so, I'm in the same case.

**Comment by jimmywarting** [comment]
IE11 understand some es6, `const` for example

**Comment by letoss** [comment]
@jimmywarting Maybe, maybe not. I think Edge understand some ES6. Anyway, the inconsistency in punycode still being there, because there is a _punycode.es6.js_ file, anyone will asume that _punycode.js_ is not compiled in ES6.

**Comment by mathiasbynens** [comment]
From the README:

> The current version supports recent versions of Node.js only. It provides a CommonJS module and an ES6 module. For the old version that offers the same functionality with broader support, including Rhino, Ringo, Narwhal, and web browsers, see [v1.4.1](https://github.com/bestiejs/punycode.js/releases/tag/v1.4.1).
