### ISSUE TITLE
Wrong conversion of secondary set of emojis (UCS2)

### ISSUE THREAD

**Issue by omaralvaradoluna** [bestiejs/punycode.js#81]
when i run the punycode.ucs2.decode

("This is a message with emoji 😊 ⚽ ⛄🎸  😆) 😇 😈 😉 😊 😋 😌 😍")

i'm obtaining numbers greater than 0xFFFF (65536) . That is wrong because we need to convert between code points and surrogate pairs as document https://mathiasbynens.be/notes/javascript-encoding

The inverse function runs without problem.

It looks like it is happening with secondary set of emojis in the document.

http://www.unicode.org/Public/emoji/1.0/emoji-data.txt

**Comment by mathiasbynens** [comment]
> i'm obtaining numbers greater than 0xFFFF (65536) .

That’s the point: https://github.com/bestiejs/punycode.js#punycodeucs2decodestring

What output would you expect?
